spring.application.name=springboot-muc5


server.port=8070

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=graphql_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.graphql.graphiql.enabled=true
spring.graphql.cors.allowed-origins=*